package Exceptions;

public class Module6Quiz {
    void myFunc(int a, int b) {
        try {
            System.out.println(a / b);
        } catch (Exception e) {
            System.out.println("Error");
        }
    }
}
